# Site settings
title: My Website
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social Media Links
twitter_username: fancykrakenstudios
github_username: eladrin201
facebook_pageid: fancykrakenstudios
google_username: +Fancykrakenstudios #please be sure to include the '+' before your username!

# Build settings
markdown: kramdown
